In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
N, p = 1,0.61
binomial = stats.binom(N,p)

In [3]:
Ntrials = 100
NSamples = 20


Matrix = []

for i in range(NSamples):
    Matrix.append(binomial.rvs(Ntrials)) 

Matrix = np.array(Matrix)
    
print(Matrix)

[[1 1 0 ... 0 1 1]
 [0 0 0 ... 0 1 1]
 [0 1 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 1 0]
 [1 1 0 ... 0 1 0]
 [0 1 1 ... 1 1 0]]


In [4]:
# Z value from the confidence level


Z = stats.norm(0,1).ppf(0.95)
#Z = stats.norm(0,1).cdf(0.05)
print(Z)

1.6448536269514722


In [5]:
# calculamos la media muestral por columnas

mean_ = np.zeros(NSamples)

for i in range(NSamples):
    mean_[i] = np.average(Matrix[i])
    
print(mean_)

[0.55 0.54 0.48 0.67 0.6  0.67 0.63 0.67 0.67 0.55 0.63 0.62 0.59 0.64
 0.7  0.55 0.66 0.54 0.54 0.63]


In [6]:
# Ahora calculamos el invervalo de confianza

Intervalo = np.zeros((NSamples,2))


for i in range(NSamples):
    Intervalo[i][0] = mean_[i] - Z*np.sqrt(p*(1-p)/Ntrials)
    Intervalo[i][1] = mean_[i] + Z*np.sqrt(p*(1-p)/Ntrials)
    
print(Intervalo)

[[0.46977227 0.63022773]
 [0.45977227 0.62022773]
 [0.39977227 0.56022773]
 [0.58977227 0.75022773]
 [0.51977227 0.68022773]
 [0.58977227 0.75022773]
 [0.54977227 0.71022773]
 [0.58977227 0.75022773]
 [0.58977227 0.75022773]
 [0.46977227 0.63022773]
 [0.54977227 0.71022773]
 [0.53977227 0.70022773]
 [0.50977227 0.67022773]
 [0.55977227 0.72022773]
 [0.61977227 0.78022773]
 [0.46977227 0.63022773]
 [0.57977227 0.74022773]
 [0.45977227 0.62022773]
 [0.45977227 0.62022773]
 [0.54977227 0.71022773]]


In [7]:
# Vamos a verificar que el 95 de las veces el valor 0.61 está contenido en el intervalo

count = 0

for i in range(NSamples):
    
    if Intervalo[i][0] < p and Intervalo[i][1] > p:
        count += 1
        
    else:
        print(Intervalo[i])
        
print(float(count)/float(NSamples))

[0.39977227 0.56022773]
[0.61977227 0.78022773]
0.9
