In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
N, p = 1,0.61
binomial = stats.binom(N,p)

In [3]:
Ntrials = 12
NSamples = 30


Matrix = []

for i in range(NSamples):
    Matrix.append(binomial.rvs(Ntrials)) 

Matrix = np.array(Matrix)
    
print(Matrix)

[[1 0 0 0 1 1 0 1 1 1 1 0]
 [1 0 1 1 0 0 1 1 0 1 1 1]
 [1 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1]
 [1 0 0 0 0 1 1 1 0 1 1 0]
 [1 0 1 0 0 1 1 0 1 0 1 1]
 [1 1 1 0 1 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0 1]
 [1 0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 1 0 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 1 0 1 1]
 [1 0 1 1 1 1 0 1 1 1 0 1]
 [0 1 0 0 0 0 1 0 1 1 1 1]
 [1 0 1 1 1 0 1 0 1 1 0 0]
 [1 0 1 0 0 1 0 1 0 0 0 1]
 [0 0 1 1 0 0 0 1 1 0 0 1]
 [0 1 0 0 1 0 1 1 0 0 1 1]
 [0 0 1 0 1 1 1 0 0 0 1 1]
 [1 0 1 0 0 1 1 1 1 0 1 0]
 [1 1 1 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 0 1 1 0 1 0]
 [1 0 1 0 1 1 1 1 0 1 1 1]
 [0 0 1 0 1 0 0 1 0 0 1 1]
 [1 0 1 1 1 0 1 1 0 0 1 0]
 [0 1 1 1 1 1 0 1 1 0 1 1]
 [1 1 1 0 1 1 0 1 0 0 0 0]
 [1 1 1 1 1 0 0 1 0 1 1 1]
 [1 0 1 1 1 1 0 0 1 1 1 1]]


In [4]:
# Z value from the confidence level


Z = stats.norm(0,1).ppf(0.95)
#Z = stats.norm(0,1).cdf(0.05)
print(Z)

1.6448536269514722


In [5]:
# calculamos la media muestral por columnas

mean_ = np.zeros(NSamples)

for i in range(NSamples):
    mean_[i] = np.average(Matrix[i])
    
print(mean_)

[0.58333333 0.66666667 0.75       0.91666667 0.5        0.58333333
 0.66666667 0.25       0.41666667 0.66666667 0.83333333 0.75
 0.83333333 0.75       0.5        0.58333333 0.41666667 0.41666667
 0.5        0.5        0.58333333 0.83333333 0.58333333 0.75
 0.41666667 0.58333333 0.75       0.5        0.75       0.75      ]


In [6]:
# Ahora calculamos el invervalo de confianza

Intervalo = np.zeros((NSamples,2))


for i in range(NSamples):
    Intervalo[i][0] = mean_[i] - Z*np.sqrt(p*(1-p)/Ntrials)
    Intervalo[i][1] = mean_[i] + Z*np.sqrt(p*(1-p)/Ntrials)
    
print(Intervalo)

[[0.35173584 0.81493083]
 [0.43506917 0.89826416]
 [0.51840251 0.98159749]
 [0.68506917 1.14826416]
 [0.26840251 0.73159749]
 [0.35173584 0.81493083]
 [0.43506917 0.89826416]
 [0.01840251 0.48159749]
 [0.18506917 0.64826416]
 [0.43506917 0.89826416]
 [0.60173584 1.06493083]
 [0.51840251 0.98159749]
 [0.60173584 1.06493083]
 [0.51840251 0.98159749]
 [0.26840251 0.73159749]
 [0.35173584 0.81493083]
 [0.18506917 0.64826416]
 [0.18506917 0.64826416]
 [0.26840251 0.73159749]
 [0.26840251 0.73159749]
 [0.35173584 0.81493083]
 [0.60173584 1.06493083]
 [0.35173584 0.81493083]
 [0.51840251 0.98159749]
 [0.18506917 0.64826416]
 [0.35173584 0.81493083]
 [0.51840251 0.98159749]
 [0.26840251 0.73159749]
 [0.51840251 0.98159749]
 [0.51840251 0.98159749]]


In [7]:
# Vamos a verificar que el 95 de las veces el valor 0.61 está contenido en el intervalo

count = 0

for i in range(NSamples):
    
    if Intervalo[i][0] < p and Intervalo[i][1] > p:
        count += 1
        
print(float(count)/float(NSamples))

0.933333333333
